name: Deploy to Host

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jzweifel/gatsby-cli-github-action@master
      - env:
        CONTENFUL_SPACE_ID: {{secrets.CONTENFUL_SPACE_ID}}
        CONTENTFUL_ACCESS_TOKEN: {{secrets.CONTENTFUL_ACCESS_TOKEN}}
        

