on:
    push:
      branches: [master]
      
jobs:
    build:
      runs-on: ubuntu-18.04
      steps:
        - name: Set Environment
        - shell: bash
          run: |
            export CONTENTFUL_SPACE_ID={{secrets.CONTENTFUL_SPACE_ID}} |
            echo $CONTENTFUL_SPACE_ID |
            export CONTENTFUL_ACCESS_TOKEN={{secrets.CONTENTFUL_ACCESS_TOKEN}} |
            echo $CONTENTFUL_ACCESS_TOKEN |

        - name: Checkout master
        - uses: actions/checkout@master

        - name: Setup Node
          uses: actions/setup-node@master
          with:
            node-version: '12.x'
        
        - run: npm ci
        - run: npm run build