on:
    push:
      branches: [master]
      
jobs:
    build:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@master

        - uses: actions/setup-node@master
          with:
            node-version: '12.x'
        
        - run: npm ci
        - run: npm run build
          env:
            spaceId: ${{secrets.CONTENTFUL_SPACE_ID}}
            accessToken: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}