on:
    push:
      branches: [master]
      
jobs:
    build:
      runs-on: ubuntu-18.04
      steps:
        - uses: actions/checkout@master

        - uses: actions/setup-node@master
          with:
            node-version: '12.x'
        
        - run: npm install
        - run: npm run clean
        - run: npm run build
          env:
            CONTENTFUL_SPACE_ID: ${{secrets.CONTENTFUL_SPACE_ID}}
            CONTENTFUL_ACCESS_TOKEN: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}

        - uses: actions/upload-artifact@master
          if: failure()
          with:
            name: error
            path: /home/runner/.npm/_logs/