on:
    push:
      branches: [master]
      
jobs:
    build:
      runs-on: ubuntu-18.04
      steps:
        - run: echo $CONTENTFUL_SPACE_ID $CONTENTFUL_ACCESS_TOKEN
          env:
            CONTENTFUL_SPACE_ID: Hello
            CONTENTFUL_ACCESS_TOKEN: World
        
        - uses: actions/checkout@master

        - uses: actions/setup-node@master
          with:
            node-version: '12.x'
        
        - run: npm ci
        - run: npm run build